# Site settings
title: Katuma Blog
header-img: img/home-bg.jpg
email: info@katuma.org
copyright_name: Katuma
description: "Ahórrate los intermediarios, compra directamente a los productores."
baseurl: ""
url: "http://katuma.org"
twitter_username: katuma_org
github_username:  coopdevs/katuma
facebook_username:  
email_username:  info@katuma.org

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-48794646-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
